### PR TITLE
issue#3 Added CI

### PR DESCRIPTION
**Pull request by danyloid**
Closes: https://github.com/flam-flam/submission-service/issues/3
Closes: https://github.com/flam-flam/submission-service/issues/9

Per discussion here: https://github.com/flam-flam/comment-service/pull/11#discussion_r1141480029
- Cleaned up the `Dockerfile`
- Switched to the `mcr.microsoft.com/dotnet/nightly/sdk:8.0-preview` to leverage support of the `--platform` switch for `linux/arm64` target
- Added workflow to be triggered on `push`
  - `test` job to execute `dotnet test`. Pipeline should be terminated if the job fails. 
  - `version` job to resolve a "version" to use as a Docker image tag - should create a semver tag if executed on `main`, use current branch name otherwise
  - `build` job - publishes image with version resolved in the `version` job & 'latest" if on main

### CODE REVIEW

**Comment by timberhill** [comment]
Just making sure we're on the same page after the chat, here is the outline of the planned workflow:

```
on: push

1. Generate a semver repo tag - only main branch
2. Run tests - always
3. Build image - always
4. Push image
   - tag: semver & 'latest" on main (same as workflows in other services)
   - tag: branch_name if not on main
```

Getting the branch name in a workflow: https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions

@danyloid lmk / edit if I am missing anything

**Comment by danyloid** [comment]
@timberhill made the changes. 
The only deviation here - I think test job should be the first to run, as it validates the app to an extent. 
If it fails - I'd rather not push a tag (on `main`, does not really matter on feature branches)

**Review by timberhill — APPROVED** [review]
Noice https://github.com/flam-flam/submission-service/pkgs/container/submission/78736959?tag=issue_3-added-workflow

:duck:

**Comment by danyloid** [comment]
Thanks for linking the image, should have done that. 

Not quite sure what the duck means though, hopefully it’s something good :)

**Comment by timberhill** [comment]
It's the duck of approval 

```
 /^^^^^^^^^^\
|  APPROVED!   \
 \_____________>🦆 
```

**Comment by danyloid** [comment]
And we have the `latest` too: https://github.com/flam-flam/submission-service/pkgs/container/submission/78761578?tag=0.1.0

**Pull request merged**
